// app/layout.tsx

import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = GeistSans;
const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
       
        <div className="bg-[#1A202C] text-[#a0aec0] min-h-screen">
          <Navbar links={["Home", "News", "Launches", "Contact", "About"]} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
